platform :ios, '10.0'

target 'WebSocketsTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WebSocketsTest
	pod 'SnapKit', '~> 5.0.0'
	pod 'Starscream', '~> 4.0.0'	
end
